apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  selector:
    app: nginx # Targets the pods with the label 'app: nginx' (from the Deployment)
  type: LoadBalancer # Triggers the creation of an AWS Load Balancer
  ports:
    - protocol: TCP
      port: 80 # The port the Load Balancer listens on
      targetPort: 80 # The port the container is listening on (Nginx default)
